---
- hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-17-jdk
        - wget
        - unzip

    - name: Download and Install SonarQube
      shell: |
        wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.9.0.43852.zip
        unzip sonarqube-8.9.0.43852.zip -d /opt/
        mv /opt/sonarqube-8.9.0.43852 /opt/sonarqube

    - name: Create SonarQube user
      user:
        name: sonar
        system: yes

    - name: Set SonarQube permissions
      command: chown -R sonar:sonar /opt/sonarqube

    - name: Create SonarQube service
      copy:
        dest: /etc/systemd/system/sonarqube.service
        content: |
          [Unit]
          Description=SonarQube service
          After=syslog.target network.target

          [Service]
          Type=forking
          ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
          ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
          User=sonar
          Group=sonar
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable SonarQube service
      systemd:
        name: sonarqube
        state: started
        enabled: yes
