Vagrant.configure("2") do |config|
  # Jenkins VM
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/focal64"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.50.10"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    jenkins.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provisioning/jenkins.yml"
      ansible.inventory_path = "provisioning/inventory.yml"
    end
  end

  # Kubernetes Master VM
  config.vm.define "k8smaster" do |k8s|
    k8s.vm.box = "ubuntu/focal64"
    k8s.vm.hostname = "k8smaster"
    k8s.vm.network "private_network", ip: "192.168.50.11"
    k8s.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    k8s.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provisioning/k8smaster.yml"
      ansible.inventory_path = "provisioning/inventory.yml"
    end
  end

  # Kubernetes Slave VM
  config.vm.define "k8sslave" do |k8sslave|
    k8sslave.vm.box = "ubuntu/focal64"
    k8sslave.vm.hostname = "k8sslave"
    k8sslave.vm.network "private_network", ip: "192.168.50.12"
    k8sslave.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    k8sslave.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provisioning/k8s_slave.yml"
      ansible.inventory_path = "provisioning/inventory.yml"
    end
  end
end
